### ISSUE TITLE
添加腾讯视频cookie 之后，运行 出现以下错误

### ISSUE THREAD

**Issue by wishcaiji** [Sunert/Scripts#49]
开始【腾讯新闻账号1】

❗️腾讯新闻, 错误!
TypeError: Cannot read property '0' of null
    at /home/runner/Scripts/Task/txnews.js:117:53
    at Object.<anonymous> (/home/runner/Scripts/Task/txnews.js:144:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by Sunert** [comment]
TXNEWS_SIGN这个地址你有没有填错

**Comment by wishcaiji** [comment]
cookie能抓取出来。 主要是格式问题，请问格式是怎样的？
  是cookie 后面这一段  还是这种格式  {"Cookie": "后面这一段"}

**Comment by wishcaiji** [comment]
我填写的是这个   ， 正确吗
{"Cookie": "open_access_token=39C75007A4CA26D56370AE456D6CACED;vqq_access_token=39C75007A4C236D56370AE456D6CACED;open_openid=E6F80C0B9377BDBC47E265A5D3E29022;vqq_openid=E6F80C0B9377BDBC47E265A5D3E293C2;open_appid=100383922;vqq_appid=100383922;open_pay_token=DC2CA707DFE0EC9753DAC4ED23E66A7C;vqq_pay_token=DC2CA707DFE0EC9753DAC4ED23E66A7C;uin=3219904322;luin=123456789;logintype=11;suid=8QMd3H9U5IQYuj3b;main_login=qq"}
